KiTakipApi/KiTakipApi/Controllers/WLoginController.cs
using KiTakipApi.Data;
using KiTakipApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using KiTakipApi.Models.Login;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using Azure.Core;

namespace KiTakipApi.Controllers
{
    public class WLoginController : Controller
    {
        private readonly DataContext _context;

        public WLoginController(DataContext context)
        {
            _context = context;
        }


        [HttpPost]
        public async  Task<IActionResult> WLogin(WAdminLogin login)
        {

            var admin = await _context.AdminUsers.FirstOrDefaultAsync(p => p.Email == login.Email);
            if (admin == null)
            {
                return NotFound();
            }

            if (!VerifyPasswordHash(login.Password, admin.PassHash, admin.PassSalt))
            {
                return BadRequest("Wrong password.");
            }

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Sid, admin.Id.ToString()),
                new Claim(ClaimTypes.Name, "Admin"),
                new Claim(ClaimTypes.Email, admin.Email),
                new Claim(ClaimTypes.Role, "Admin"),
            
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = login.KeepLoggedIn
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity), properties);

            return RedirectToAction("Index", "Home");
        }

        //Login 
        public ActionResult WLogin()
        {
            ClaimsPrincipal claimsUser = HttpContext.User;

            if (claimsUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            
            return View();
        }
        private bool VerifyPasswordHash(string password, byte[] passwordHash, byte[] passwordSalt)
        {
            using (var hmac = new HMACSHA512(passwordSalt))
            {
                var computedHash = hmac.ComputeHash(System.Text.Encoding.UTF8.GetBytes(password));
                return computedHash.SequenceEqual(passwordHash);
            }
        }
    }
}

KiTakipApi/KiTakipApi/Views/WLogin/WLogin.cshtml
@model KiTakipApi.Models.Login.WAdminLogin

@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>
<form asp-controller="WLogin" asp-action="WLogin" method="post">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>

        @if (ViewBag.Message != null)
        {
            <div class="text-danger">@ViewBag.Message</div>
        }

        <div class="form-group">
            <label asp-for="Email" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Password" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <div style="display:flex ">
            <label asp-for="KeepLoggedIn" class="control-label"></label>
            <input type="checkbox" asp-for="KeepLoggedIn"  />
            <span asp-validation-for="KeepLoggedIn" class="text-danger"></span>
            </div>
            
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>